
// The list of arrays of possible characters for password

var special = ["!@#$%^&*()-_=+/"];
var numbers = ["0123456789"];
var lowerCase = ["abcdefghijklmnopqrstuvwxyz"];
var upperCase = ["ABCDEFGHIJKLMNOPQRSTUVWXYZ"];

// Refers to the text box that shows the gerneated password

var yourPassword = document.getElementById ("yourPassword");

// Refers to the botton that the user clicks to generates the password

var submit = document.getElementById("clickSubmit");

// The variable's values for the password are to be determiend in the functions

var characterNumber = "";

var characters = "";


// User inputs the desired length of password 

function answerCharacterNumber () {
    var plength = Number(prompt("Enter the length of your password between 8 and 128?"));
    if (plength == plength > 8 || plength < 128); { 
            characterNumber = plength;  
        }
    }

// User has the option of including numbers in password

function answerNumbers() {
    var numbersYes = confirm("Would you like to have numbers in your password?");
    if (numbersYes == true) {
        characters = characters + numbers;
    }
}


// User has the option of including upper case letters in password

function answerUpperCase() {
    var upperCaseYes = confirm("Would you like to have upper case letters in your password?");
    if (upperCaseYes == true) { 
        characters = characters + upperCase;
    }
}


// User has the option of including lower case letters in password

function answerLowerCase() {
    var lowerCaseYes = confirm("Would you like to have lower case letters in your password?");
    if (lowerCaseYes == true) {
        characters = characters + lowerCase; 
    }
}


// User has the option of including special characters in password

function answerSpecial() {
    var specialCharactersYes = confirm("Would you like to have special characters in your password?");
    if (specialCharactersYes == true) {
        characters = characters + special;
    }
}


// The user's choices result in password generated by the given values

function clickSubmit() {

    answerCharacterNumber ();
    answerNumbers ();
    answerUpperCase ();
    answerLowerCase ();
    answerSpecial ();
    yourPassword.value = password(characterNumber, characters);
   
}

// The loop takes the values determind from the previous 

function password(length, characters) {
    var password = "";
    for(var i = 0; i < length; i++) {
        password = password + characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return password;
}


// The user has the option to copy the password that was generated from the loop to clipbaord

function clickCopy() {
    var copyText = document.getElementById("yourPassword")
    copyText.select();
    copyText.setSelectionRange(0, 99999)
    document.execCommand("copy");
    alert("Copied the Password: " + copyText.value);

}